apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: dev
  annotations:
    # Anotasi Nginx Controller: Rewrite target ke root path /
    nginx.ingress.kubernetes.io/rewrite-target: /
    
    # Anotasi Nginx Controller: Memaksa redirect HTTP ke HTTPS (optional)
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
    
spec:
  # BAGIAN TLS (Tersedia jika Anda sudah membuat Secret sbiz-tls-secret)
  #tls:
  #- hosts:
  #  - dev.sbiz-app.my.id
  #  secretName: sbiz-tls-secret 
    
  # --- DEFAULT BACKEND DITAMBAHKAN DI SINI ---
  defaultBackend:
    service:
      name: nginx-service
      port:
        number: 80
        
  rules:
  - host: reseller.sbiz-app.my.id 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80