apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: dev
  annotations:
    cert-manager.io/issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
    
spec:
  # --- BLOK TLS WAJIB ADA UNTUK MENDAPATKAN SERTIFIKAT ---
  tls:
  - hosts:
    - reseller.sbiz-app.my.id
    secretName: reseller-sbiz-tls-secret-vhvqd-vkpr9-kbtxk  # Secret yang akan dibuat oleh cert-manager
    
  defaultBackend:
    service:
      name: nginx-service
      port:
        number: 80
        
  rules:
  - host: reseller.sbiz-app.my.id 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80